import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#131316',
        surface: {
          DEFAULT: '#131316',
          high: '#2a2a2d',
        },
        'surface-dim': '#131316',
        'surface-bright': '#39393c',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1b1b1e',
        'surface-container': '#1f1f22',
        'surface-container-high': '#2a2a2d',
        'surface-container-highest': '#353438',
        'surface-variant': '#353438',
        'surface-glass': 'rgba(27, 27, 31, 0.7)',
        'surface-border': 'rgba(255, 255, 255, 0.08)',
        'on-surface': '#e4e1e6',
        'on-surface-variant': '#bac9cc',
        'on-background': '#e4e1e6',
        'inverse-surface': '#e4e1e6',
        'inverse-on-surface': '#303033',
        outline: '#849396',
        'outline-variant': '#3b494c',
        'surface-tint': '#00daf3',
        primary: '#c3f5ff',
        'on-primary': '#00363d',
        'primary-container': '#00e5ff',
        'on-primary-container': '#00626e',
        'primary-fixed': '#9cf0ff',
        'primary-fixed-dim': '#00daf3',
        'on-primary-fixed': '#001f24',
        'on-primary-fixed-variant': '#004f58',
        'inverse-primary': '#006875',
        secondary: '#c8c5cb',
        'on-secondary': '#303034',
        'secondary-container': '#47464b',
        'on-secondary-container': '#b6b4b9',
        'secondary-fixed': '#e4e1e7',
        'secondary-fixed-dim': '#c8c5cb',
        'on-secondary-fixed': '#1b1b1f',
        'on-secondary-fixed-variant': '#47464b',
        tertiary: '#aaffc3',
        'on-tertiary': '#00391d',
        'tertiary-container': '#00ee8a',
        'on-tertiary-container': '#006638',
        'tertiary-fixed': '#5bffa1',
        'tertiary-fixed-dim': '#00e383',
        'on-tertiary-fixed': '#00210e',
        'on-tertiary-fixed-variant': '#00522c',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        // Elite Performance Reimagined accent tokens (Stitch)
        'performance-cyan': '#00E5FF',
        'obsidian-dark': '#0F0F12',
        'charcoal-surface': '#1B1B1F',
        'success-emerald': '#00C853',
        'attention-coral': '#FF5252',
        'glass-stroke': 'rgba(255, 255, 255, 0.08)',
        // semantic aliases used across the app
        success: '#00C853',
        warning: '#FFB300',
        'alert-red': '#FF5252',
        border: {
          DEFAULT: 'rgba(255, 255, 255, 0.08)',
          luminous: 'rgba(255, 255, 255, 0.08)',
        },
        text: {
          primary: '#e4e1e6',
          secondary: '#bac9cc',
          tertiary: '#849396',
          muted: '#849396',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        gutter: '1rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Geist', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'data-mono': ['14px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
      backdropBlur: {
        xl: '20px',
      },
    },
  },
  plugins: [],
}
export default config
