export interface User {
  id: string
  name: string | null
  email: string
  bio: string | null
  phone: string | null
  instagram: string | null
  youtube: string | null
  avatar_url: string | null
  specialties: string[] | null
  createdAt: string
}

export interface Student {
  id: string
  name: string
  email: string | null
  phone: string | null
  birthdate: string | null
  city: string | null
  state: string | null
  goal: string | null
  level: 'iniciante' | 'intermediario' | 'avancado'
  daysPerWeek: number
  sessionDuration: number
  restrictions: string | null
  equipment: string | null
  notes: string | null
  status: 'ativo' | 'pausado' | 'inativo'
  mfitId: string | null
  lastContactAt: string | null
  createdAt: string
  updatedAt: string
}

export interface Photo {
  id: string
  studentId: string
  url: string
  angle: string | null
  takenAt: string
}

export interface PhysicalAssessment {
  id: string
  studentId: string
  weight: number
  height: number
  age: number
  triceps: number | null
  subscapular: number | null
  pectoral: number | null
  midaxillary: number | null
  suprailiac: number | null
  abdominal: number | null
  thigh: number | null
  bodyFatPercent: number | null
  leanMassKg: number | null
  fatMassKg: number | null
  bmi: number | null
  classification: string | null
  waistCm: number | null
  hipCm: number | null
  chestCm: number | null
  armCm: number | null
  thighCm: number | null
  calfCm: number | null
  notes: string | null
  assessedAt: string
  createdAt: string
}

export interface Exercise {
  id: string
  name: string
  muscleGroup: string
  equipment: string | null
  level: string | null
  type: string | null
  description: string | null
  primaryMuscles: string | null
  secondaryMuscles: string | null
  steps: string[] | null
  safetyTip: string | null
  videoUrl: string | null
  imageUrl: string | null
  isCustom: boolean
}

export interface Workout {
  id: string
  studentId: string
  title: string
  content: string | null
  status: 'rascunho' | 'aprovado' | 'enviado_mfit'
  mfitSyncedAt: string | null
  createdAt: string
}

export interface WorkoutSession {
  id: string
  workoutId: string
  name: string
  order: number
  warmup: string | null
}

export interface WorkoutExercise {
  id: string
  sessionId: string
  exerciseId: string | null
  name: string
  sets: number
  reps: string
  rest: number
  notes: string | null
  muscleGroup: string | null
  videoUrl: string | null
  order: number
}

export interface WorkoutExecution {
  id: string
  studentId: string
  workoutId: string
  sessionId: string
  startedAt: string
  finishedAt: string | null
  duration: number | null
  notes: string | null
}

export interface SetLog {
  id: string
  executionId: string
  exerciseId: string
  setNumber: number
  reps: number
  weight: number
  completedAt: string
}

export interface FollowUp {
  id: string
  studentId: string
  message: string
  channel: string
  status: string
  autoGenerated: boolean
  sentAt: string
}

export interface Settings {
  id: string
  smtpHost: string | null
  smtpPort: number | null
  smtpUser: string | null
  smtpPass: string | null
  smtpFrom: string | null
  followUpTemplate: string | null
  autoFollowUp: boolean
  followUpHour: number
  workoutPreferences: string | null
}
