import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/lib/get-session'
import { supabaseAdmin } from '@/lib/supabase'

export async function POST(request: NextRequest) {
  const session = await getSession()
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  try {
    const { studentId, message, channel = 'manual' } = await request.json() as {
      studentId: string
      message: string
      channel?: string
    }

    await supabaseAdmin.from('FollowUp').insert({
      studentId, message, channel, status: 'enviado', autoGenerated: false, sentAt: new Date().toISOString(),
    })
    await supabaseAdmin.from('Student').update({ lastContactAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).eq('id', studentId)

    return NextResponse.json({ success: true })
  } catch (err: unknown) {
    const errMessage = err instanceof Error ? err.message : String(err)
    return NextResponse.json({ error: errMessage }, { status: 500 })
  }
}
