import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/lib/get-session'
import { supabaseAdmin } from '@/lib/supabase'

export async function POST(request: NextRequest) {
  const session = await getSession()
  if (!session) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 })
  try {
    const { studentId, studentIds, message, channel = 'manual' } = await request.json() as {
      studentId?: string
      studentIds?: string[]
      message: string
      channel?: string
    }
    const ids = Array.isArray(studentIds) && studentIds.length > 0
      ? studentIds.filter(Boolean)
      : studentId
        ? [studentId]
        : []
    const cleanMessage = typeof message === 'string' && message.trim()
      ? message.trim()
      : 'Contato realizado e registrado manualmente.'

    if (ids.length === 0) {
      return NextResponse.json({ error: 'Selecione pelo menos um aluno' }, { status: 400 })
    }

    const now = new Date().toISOString()
    const followUps = ids.map((id) => ({
      studentId: id,
      message: cleanMessage,
      channel,
      status: 'enviado',
      autoGenerated: false,
      sentAt: now,
    }))

    const { error: followUpError } = await supabaseAdmin.from('FollowUp').insert(followUps)
    if (followUpError) return NextResponse.json({ error: 'Erro ao registrar follow-up' }, { status: 500 })

    const { error: studentError } = await supabaseAdmin
      .from('Student')
      .update({ lastContactAt: now, updatedAt: now })
      .in('id', ids)
    if (studentError) return NextResponse.json({ error: 'Erro ao atualizar alunos' }, { status: 500 })

    return NextResponse.json({ success: true, updated: ids.length })
  } catch (err: unknown) {
    const errMessage = err instanceof Error ? err.message : String(err)
    return NextResponse.json({ error: errMessage }, { status: 500 })
  }
}
