import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/lib/get-session'
import { supabaseAdmin } from '@/lib/supabase'
import { escapeHtml, sanitizeString } from '@/lib/sanitize'
import nodemailer from 'nodemailer'

export async function POST(request: NextRequest) {
  const session = await getSession()
  if (!session?.user?.id) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 })
  try {
    const { studentId, message } = await request.json() as { studentId: string; message: string }

    if (!studentId || typeof studentId !== 'string') {
      return NextResponse.json({ error: 'ID do aluno é obrigatório' }, { status: 400 })
    }
    const safeMessage = sanitizeString(message, 5000)
    if (!safeMessage) {
      return NextResponse.json({ error: 'Mensagem é obrigatória' }, { status: 400 })
    }

    const { data: student } = await supabaseAdmin.from('Student').select('*').eq('id', studentId).single()
    if (!student) return NextResponse.json({ error: 'Aluno não encontrado' }, { status: 404 })

    const s = student as Record<string, unknown>
    if (!s.email) return NextResponse.json({ error: 'Aluno não possui e-mail' }, { status: 400 })

    const { data: settingsArr } = await supabaseAdmin.from('Settings').select('*').limit(1)
    const settings = settingsArr?.[0] as Record<string, unknown> | undefined

    if (!settings?.smtpHost || !settings?.smtpUser || !settings?.smtpPass) {
      return NextResponse.json({ error: 'SMTP não configurado' }, { status: 400 })
    }

    const transporter = nodemailer.createTransport({
      host: settings.smtpHost as string,
      port: (settings.smtpPort as number) || 587,
      secure: ((settings.smtpPort as number) || 587) === 465,
      auth: { user: settings.smtpUser as string, pass: settings.smtpPass as string },
    })

    const safeName = escapeHtml(String(s.name || ''))
    const escapedMessage = escapeHtml(safeMessage).replace(/\n/g, '<br/>')

    await transporter.sendMail({
      from: (settings.smtpFrom as string) || (settings.smtpUser as string),
      to: s.email as string,
      subject: `Olá ${safeName}! Acompanhamento do seu treino`,
      text: safeMessage,
      html: `<div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;"><p>${escapedMessage}</p></div>`,
    })

    await supabaseAdmin.from('FollowUp').insert({
      studentId, message: safeMessage, channel: 'email', status: 'enviado', autoGenerated: false, sentAt: new Date().toISOString(),
    })
    await supabaseAdmin.from('Student').update({ lastContactAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).eq('id', studentId)

    return NextResponse.json({ success: true })
  } catch {
    return NextResponse.json({ error: 'Erro ao enviar e-mail' }, { status: 500 })
  }
}
