import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/lib/get-session'
import { supabaseAdmin } from '@/lib/supabase'
import nodemailer from 'nodemailer'

export async function POST(request: NextRequest) {
  const session = await getSession()
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  try {
    const { studentId, message } = await request.json() as { studentId: string; message: string }

    const { data: student } = await supabaseAdmin.from('Student').select('*').eq('id', studentId).single()
    if (!student) return NextResponse.json({ error: 'Student not found' }, { status: 404 })

    const s = student as Record<string, unknown>
    if (!s.email) return NextResponse.json({ error: 'Student has no email' }, { status: 400 })

    const { data: settingsArr } = await supabaseAdmin.from('Settings').select('*').limit(1)
    const settings = settingsArr?.[0] as Record<string, unknown> | undefined

    if (!settings?.smtpHost || !settings?.smtpUser || !settings?.smtpPass) {
      return NextResponse.json({ error: 'SMTP not configured' }, { status: 400 })
    }

    const transporter = nodemailer.createTransport({
      host: settings.smtpHost as string,
      port: (settings.smtpPort as number) || 587,
      secure: ((settings.smtpPort as number) || 587) === 465,
      auth: { user: settings.smtpUser as string, pass: settings.smtpPass as string },
    })

    await transporter.sendMail({
      from: (settings.smtpFrom as string) || (settings.smtpUser as string),
      to: s.email as string,
      subject: `Olá ${s.name}! Acompanhamento do seu treino 💪`,
      text: message,
      html: `<div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;"><p>${message.replace(/\n/g, '<br/>')}</p></div>`,
    })

    // Register follow-up + update lastContactAt
    await supabaseAdmin.from('FollowUp').insert({
      studentId, message, channel: 'email', status: 'enviado', autoGenerated: false, sentAt: new Date().toISOString(),
    })
    await supabaseAdmin.from('Student').update({ lastContactAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).eq('id', studentId)

    return NextResponse.json({ success: true })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
