import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'
import nodemailer from 'nodemailer'

export async function GET(request: NextRequest) {
  const cronSecret = request.headers.get('authorization')
  if (cronSecret !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const { data: settings } = await supabaseAdmin.from('Settings').select('*').limit(1)
    const config = settings?.[0] as Record<string, unknown> | undefined
    if (!config?.autoFollowUp) return NextResponse.json({ message: 'Auto follow-up disabled' })

    const cutoff = new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString()
    const { data: students } = await supabaseAdmin
      .from('Student')
      .select('*')
      .eq('status', 'ativo')
      .or(`lastContactAt.lt.${cutoff},lastContactAt.is.null`)

    if (!students || students.length === 0) return NextResponse.json({ message: 'No students need follow-up', count: 0 })

    let sent = 0
    for (const studentRaw of students) {
      const student = studentRaw as Record<string, unknown>
      if (!student.email || !config.smtpHost) continue
      const template = (config.followUpTemplate as string) || 'Olá {nome}! Passando para saber como estão seus treinos. Continue firme! 💪'
      const message = template
        .replace('{nome}', student.name as string)
        .replace('{objetivo}', (student.goal as string) || '')
        .replace('{dias}', String(Math.floor((Date.now() - new Date(student.createdAt as string).getTime()) / (1000 * 60 * 60 * 24))))

      try {
        const transporter = nodemailer.createTransport({
          host: config.smtpHost as string,
          port: (config.smtpPort as number) || 587,
          secure: config.smtpPort === 465,
          auth: { user: config.smtpUser as string, pass: config.smtpPass as string },
        })
        await transporter.sendMail({
          from: (config.smtpFrom as string) || (config.smtpUser as string),
          to: student.email as string,
          subject: `Acompanhamento — ${student.name}`,
          text: message,
        })
        await supabaseAdmin.from('FollowUp').insert({
          studentId: student.id,
          message,
          channel: 'email',
          status: 'enviado',
          autoGenerated: true,
          sentAt: new Date().toISOString(),
        })
        await supabaseAdmin.from('Student').update({ lastContactAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).eq('id', student.id as string)
        sent++
      } catch { /* skip failed sends */ }
    }
    return NextResponse.json({ message: 'Cron completed', sent, total: students.length })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
