-- PT Manager Initial Schema

-- User table (personal trainer profile)
CREATE TABLE IF NOT EXISTS "User" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  bio TEXT,
  phone TEXT,
  instagram TEXT,
  youtube TEXT,
  avatar_url TEXT,
  specialties TEXT[],
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Student table
CREATE TABLE IF NOT EXISTS "Student" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  birthdate DATE,
  city TEXT,
  state TEXT,
  goal TEXT,
  level TEXT NOT NULL DEFAULT 'iniciante' CHECK (level IN ('iniciante', 'intermediario', 'avancado')),
  "daysPerWeek" INTEGER NOT NULL DEFAULT 3,
  "sessionDuration" INTEGER NOT NULL DEFAULT 60,
  restrictions TEXT,
  equipment TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'pausado', 'inativo')),
  "mfitId" TEXT,
  "lastContactAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Photo table
CREATE TABLE IF NOT EXISTS "Photo" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "Student"(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  angle TEXT,
  "takenAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- PhysicalAssessment table
CREATE TABLE IF NOT EXISTS "PhysicalAssessment" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "Student"(id) ON DELETE CASCADE,
  weight NUMERIC(5,2) NOT NULL,
  height NUMERIC(5,2) NOT NULL,
  age INTEGER NOT NULL,
  triceps NUMERIC(5,2),
  subscapular NUMERIC(5,2),
  pectoral NUMERIC(5,2),
  midaxillary NUMERIC(5,2),
  suprailiac NUMERIC(5,2),
  abdominal NUMERIC(5,2),
  thigh NUMERIC(5,2),
  "bodyFatPercent" NUMERIC(5,2),
  "leanMassKg" NUMERIC(5,2),
  "fatMassKg" NUMERIC(5,2),
  bmi NUMERIC(5,2),
  notes TEXT,
  "assessedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Exercise table
CREATE TABLE IF NOT EXISTS "Exercise" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  "muscleGroup" TEXT NOT NULL,
  equipment TEXT,
  level TEXT,
  type TEXT,
  description TEXT,
  "primaryMuscles" TEXT,
  "secondaryMuscles" TEXT,
  steps TEXT[],
  "safetyTip" TEXT,
  "videoUrl" TEXT,
  "imageUrl" TEXT,
  "isCustom" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Workout table
CREATE TABLE IF NOT EXISTS "Workout" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "Student"(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT,
  status TEXT NOT NULL DEFAULT 'rascunho' CHECK (status IN ('rascunho', 'aprovado', 'enviado_mfit')),
  "mfitSyncedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- WorkoutSession table
CREATE TABLE IF NOT EXISTS "WorkoutSession" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "workoutId" UUID NOT NULL REFERENCES "Workout"(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0,
  warmup TEXT
);

-- WorkoutExercise table
CREATE TABLE IF NOT EXISTS "WorkoutExercise" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "sessionId" UUID NOT NULL REFERENCES "WorkoutSession"(id) ON DELETE CASCADE,
  "exerciseId" UUID REFERENCES "Exercise"(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  sets INTEGER NOT NULL DEFAULT 3,
  reps TEXT NOT NULL DEFAULT '10',
  rest INTEGER NOT NULL DEFAULT 60,
  notes TEXT,
  "muscleGroup" TEXT,
  "videoUrl" TEXT,
  "order" INTEGER NOT NULL DEFAULT 0
);

-- WorkoutExecution table
CREATE TABLE IF NOT EXISTS "WorkoutExecution" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "Student"(id) ON DELETE CASCADE,
  "workoutId" UUID NOT NULL REFERENCES "Workout"(id) ON DELETE CASCADE,
  "sessionId" UUID NOT NULL REFERENCES "WorkoutSession"(id) ON DELETE CASCADE,
  "startedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "finishedAt" TIMESTAMPTZ,
  duration INTEGER,
  notes TEXT
);

-- SetLog table
CREATE TABLE IF NOT EXISTS "SetLog" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "executionId" UUID NOT NULL REFERENCES "WorkoutExecution"(id) ON DELETE CASCADE,
  "exerciseId" UUID NOT NULL REFERENCES "Exercise"(id) ON DELETE CASCADE,
  "setNumber" INTEGER NOT NULL,
  reps INTEGER NOT NULL,
  weight NUMERIC(6,2) NOT NULL,
  "completedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- FollowUp table
CREATE TABLE IF NOT EXISTS "FollowUp" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "Student"(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT 'email',
  status TEXT NOT NULL DEFAULT 'pendente',
  "autoGenerated" BOOLEAN NOT NULL DEFAULT FALSE,
  "sentAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Settings table (single row)
CREATE TABLE IF NOT EXISTS "Settings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "smtpHost" TEXT,
  "smtpPort" INTEGER,
  "smtpUser" TEXT,
  "smtpPass" TEXT,
  "smtpFrom" TEXT,
  "followUpTemplate" TEXT,
  "autoFollowUp" BOOLEAN NOT NULL DEFAULT FALSE,
  "followUpHour" INTEGER NOT NULL DEFAULT 11,
  "workoutPreferences" TEXT
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_student_status ON "Student"(status);
CREATE INDEX IF NOT EXISTS idx_student_last_contact ON "Student"("lastContactAt");
CREATE INDEX IF NOT EXISTS idx_workout_student ON "Workout"("studentId");
CREATE INDEX IF NOT EXISTS idx_assessment_student ON "PhysicalAssessment"("studentId");
CREATE INDEX IF NOT EXISTS idx_followup_student ON "FollowUp"("studentId");
CREATE INDEX IF NOT EXISTS idx_execution_student ON "WorkoutExecution"("studentId");
CREATE INDEX IF NOT EXISTS idx_photo_student ON "Photo"("studentId");
