ALTER TABLE "Student"
ADD COLUMN IF NOT EXISTS age INTEGER CHECK (age IS NULL OR age BETWEEN 0 AND 130),
ADD COLUMN IF NOT EXISTS height NUMERIC(5,2) CHECK (height IS NULL OR height BETWEEN 0 AND 300);
